// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAAYa2IqVGjyPp8un1Xs66L7Fi57HrMDE',
    appId: '1:272111589238:web:11983c411e854ee0318c57',
    messagingSenderId: '272111589238',
    projectId: 'appmy-b4ff9',
    authDomain: 'appmy-b4ff9.firebaseapp.com',
    storageBucket: 'appmy-b4ff9.firebasestorage.app',
    measurementId: 'G-QP1NJCFHMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQgOi7-l8F1n0HSiISRzDu9eJobX-WFDE',
    appId: '1:272111589238:android:85e8ef7bfebb4836318c57',
    messagingSenderId: '272111589238',
    projectId: 'appmy-b4ff9',
    storageBucket: 'appmy-b4ff9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmD9z2fgwyKQTs5I34gsmzyqWb-nawYns',
    appId: '1:272111589238:ios:43f9142da28ca6aa318c57',
    messagingSenderId: '272111589238',
    projectId: 'appmy-b4ff9',
    storageBucket: 'appmy-b4ff9.firebasestorage.app',
    iosClientId: '272111589238-n5vsfm0i5psjiqacaa3lrec9eq5vr7og.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBasico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmD9z2fgwyKQTs5I34gsmzyqWb-nawYns',
    appId: '1:272111589238:ios:43f9142da28ca6aa318c57',
    messagingSenderId: '272111589238',
    projectId: 'appmy-b4ff9',
    storageBucket: 'appmy-b4ff9.firebasestorage.app',
    iosClientId: '272111589238-n5vsfm0i5psjiqacaa3lrec9eq5vr7og.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBasico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAAYa2IqVGjyPp8un1Xs66L7Fi57HrMDE',
    appId: '1:272111589238:web:12ba951be0048e71318c57',
    messagingSenderId: '272111589238',
    projectId: 'appmy-b4ff9',
    authDomain: 'appmy-b4ff9.firebaseapp.com',
    storageBucket: 'appmy-b4ff9.firebasestorage.app',
    measurementId: 'G-0JZ817HQXV',
  );
}
